# Generated by Django 5.2.6 on 2025-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_document_studentdata_document_supervisordata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='studentdata',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='supervisordata',
            new_name='supervisor',
        ),
    ]
