# Generated by Django 5.2.6 on 2025-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rename_studentdata_document_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Project Document', max_length=40),
        ),
    ]
