# Generated by Django 5.2.6 on 2025-09-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Project Document', max_length=40),
        ),
    ]
