# Generated by Django 5.2.6 on 2025-10-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_document_description_alter_document_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_time']},
        ),
    ]
