# Generated by Django 5.2.6 on 2025-10-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
    ]
